{% set name = "podaac-data-subscriber" %}
{% set version = "1.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/podaac-data-subscriber-{{ version }}.tar.gz
  sha256: c250d1009adc73920804e05b425fd9921b5656db011e4a50e7ed6386e2c4b894

build:
  entry_points:
    - podaac-data-subscriber = subscriber.podaac_data_subscriber:run
    - podaac-data-downloader = subscriber.podaac_data_downloader:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - poetry
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - packaging
    - requests
    - tenacity

test:
  imports:
    - subscriber
  commands:
    - pip check
    - podaac-data-subscriber -h
    - podaac-data-downloader -h
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/podaac/data-subscriber
  summary: PO.DAAC Data Susbcriber Command Line Tool
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kthyng
